import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// frontend@upayments.com
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/router";

import { useAppDispatch, useAppSelector } from "../redux/hooks";
import { Dashboard, Header } from "../components";

import { getProducts } from "../redux/features/productsSlice";
import { getCategories } from "../redux/features/categorySlice";
import Search from "../components/Search";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const [searchText, setSearchText] = useState("");
  const [searchDropdown, setSearchDropdown] = useState("");
  const [products, setProducts] = useState([]);

  const { productsState, category, isLoading } = useAppSelector(
    (reducer: any) => ({
      productsState: reducer.products.items,
      category: reducer.categories.items,
      isLoading: reducer.products.isLoading,
    })
  );

  useEffect(() => {
    dispatch(getProducts());
    dispatch(getCategories());
  }, []);

  useEffect(() => {
    filteredProducts();
  }, [searchText, searchDropdown]);

  const filteredProducts = () => {
    return productsState
      .filter((product: any) => {
        if (searchText === "") {
          return true;
        }
        return product.name.toLowerCase().includes(searchText.toLowerCase());
      })
      .filter((product: any) => {
        if (searchDropdown === "") {
          return true;
        }
        return product.category
          ?.toLowerCase()
          .includes(searchDropdown?.toLowerCase());
      });
  };

  const handleGoToAddPAge = () => {
    router.push("/add-product");
  };

  return (
    <div className="justify-center items-center flex flex-col">
      <Head>
        <title>Upayments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <Header title="Home" subtitle="React Task" />
        <Search
          onChangeDropdown={setSearchDropdown}
          onChangeText={setSearchText}
        />
        <Dashboard data={filteredProducts()} />
      </div>

      <button
        className="fixed bottom-4 md:right-20 md:bottom-20 bg-black rounded-3xl p-4"
        onClick={handleGoToAddPAge}
      >
        <p className="text-white text-2xl">Add Product</p>
      </button>
    </div>
  );
};

export default Home;
