import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// frontend@upayments.com
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

import productsSlice, { getProducts } from "../redux/features/productsSlice";
import { useAppDispatch, useAppSelector } from "../redux/hooks";
import { Dashboard, Header } from "../components";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getProducts());
    console.log("useEffect initialized");
    return () => {
      console.log("useEffect destroyed");
    };
  }, []);

  const { productsState } = useAppSelector((reducer: any) => ({
    productsState: reducer.products.items,
  }));

  console.log(productsState);

  return (
    <div className="justify-center items-center flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="Home" subtitle="React Task" />
      <Dashboard data={productsState}> </Dashboard>
    </div>
  );
};

export default Home;
